language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy versions
  #- "pypy3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .

# command to run tests
script: 
  - python -m unittest discover test


