
import cython_swps3

x = cython_swps3.AlignmentEnvironment()
x.readFromFile('516.dat')

#39.57457847	39.54408533	45.34733903	288.dat
s1 = 'KQTASGGRPLGNMPAYTPLYENVGTSIFSKSQKEDALYRIKYEYGNGTQHATMTGGINRAATVGARPAVRPETKVKIYHDLLICYGLTVVGMEPEDIQLCASSFKYFPEYYFDYQESAINEFMCFGKIKRHSRHRYVLAGWRVATHWVITQTLNELERPVQAIRLETISSSQELIFEVLNPFNIRIRFYDHTKHRHRFGCTRLDMKALVRLLLQFAVLGSTAKDIQRSPINTDLALKLAERRNLNPNVLK'
s2 = 'RIDLSSRLQTHHRRQKTGETTLYRGDRGYRRGTDVPKLCGPETDDTAVEFDGDKFSGRMGVDETSDKPFVRISGVLYRHALIVLNFSQAGAVSDLQKELTVANINYNPSALPDPTVLVGWVQNVPHETLFKKHGQDHESAVQVIRTFAGDGMEFFDSDTRKNYSKGRPAIWIPVCRPEMMRNLSVLIGNGVYASSEGEFGQPIHAKTEASHRDMTLYLVLSGYTPNISKGALE'

#1.797693135e+308	642.5755307	999.6168591	343.dat
s3 = 'GCANLVSRLENNSRLLNRDLIAVTIGAIVYKDPHAGALRSLHGIWRFIKYLDGLNTVMTSLKSTKGITNTTDWCQHTMAVAEGQFNSAAIAACEKWVMKIDIVWDLIPSHPAVLCVDNTFKSRMPGFLLEITKFWAASYEISLSYEETAATLIARGYALFGAATRAVIIQPDTIKNQMEGTNDAPKPLSSGVVWESQTFCACYGWFPGTAKCCTVCDFLLTGEELPNDLQTIANELFGTDQPFTNFNGIG'
s4 = 'GGFNPFRQNLKVRQELNGKIITPTLLIVPVACIVYTEPHVGETVTNNNALRYVHGIWGFTKYSNGINTLFTNTRTVEGLAFATDWCEHTMVPLTKRGKIKSATIGACGARLMKYQQVGDLKSASEDKLCVDITLDLRQTGFLMTITKFWAGNYEVSISYHETSLYLKKRAFALFTTDTVAVIIQPDAFKNAMGGTNSTKKPVNQGVNWSDQDFCACYGIFPGTDTCCTICDFILTGDELPDDLTTKLKEDFYTAKPYTNRNGIL'

#58.59143969	58.48955508	59.96561999	491.dat
s5 = 'GTSTLKNAQKERSVLMELVQFEENSQLNNYIFKAPPEISVAGYLQNIVVNGQVQRGPEGYKFHEIEAPEDSYKLIRFLADLVCDTASRRACEWTRKFVTGDSVPGHLLVEYLKASPEATQVTPIKQKKDYLTKNKFRATKKFLSSIVKALSSKIDKLADINLIGTEKRIDKKNKSVLDAAELVWIYVERRIKDGAEEFRVHKYVQNTGKTEYNAKDAVPTDPEYSAIQRAFPLCLEWFEMYMFAQETQAL'
s6 = 'GSVTCNELANGPKCLVNFDTYRDESPVSQRSSKSMPVQDAYIDGPGLLPLLSALSYLILYEKAAGLHPADKPMSHGTCKGKMIFMLMNQVDDMAKRKPSDLYLQFLVGIPHVSTLDADHRTISHAVVYVHPNINKANIKKAITYEYLDKILDIGMLNHDTLERDNTLGGSVSGQLSHSPENDNEVIKLFLTHRCSPRASQSRRNHLARIKGLANLKFGSWDDPPMNVGLMATKRAYRQLTLALDGETKGGM'

print cython_swps3.normalizedAlignScalar(s1, s2, x)
#print cython_swps3.normalizedAlignByte(s1, s2, x)
print cython_swps3.normalizedAlignShort(s1, s2, x)

print cython_swps3.normalizedAlignScalar(s3, s4, x)
#print cython_swps3.normalizedAlignByte(s1, s2, x)
print cython_swps3.normalizedAlignShort(s3, s4, x)

print cython_swps3.normalizedAlignScalar(s5, s6, x)
#print cython_swps3.normalizedAlignByte(s1, s2, x)
print cython_swps3.normalizedAlignShort(s5, s6, x)


#print "int16: GapOpen = %f, GapExt = %f, Threshold = %f" % (x.int16_gapOpen, x.int16_gapExt, x.threshold)
#print x.int16_Matrix
#print x.shortFactor()

#x.columns = "A"
#x.readFromFile("onlyA.dat")

#print cython_swps3.normalizedAlignScalar("A", "A", x)
#print cython_swps3.normalizedAlignShort("A", "A", x)
#print cython_swps3.normalizedAlignByte("A", "A", x)

#envs = cython_swps3.readAlignmentEnvironments('/home/machine/repos/students/2014_Ferenc_Galko_SWPS3_PY/swps3_python_extended/python/matrices')

#print cython_swps3.binaryAlignNormalized(envs, s1, s2)